---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
    labels:
      - "dependabot"
      - "gha deps"
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependabot"
      - "go deps"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      storybook:
        patterns:
          - "@storybook*"
          - "storybook"
      emotion:
        patterns:
          - "@emotion*"
      mui:
        patterns:
          - "@mui*"
      tyescript-eslint:
        patterns:
          - "@typescript-eslint*"
      eslint:
        patterns:
          - "eslint*"
    open-pull-requests-limit: 10
    labels:
      - "dependabot"
      - "npm deps"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    labels:
      - "dependabot"
      - "docker deps"
    open-pull-requests-limit: 10
