---
version: "3"

services:
  zeevision:
    build: ./
    image: "zeevision:latest"
    container_name: zeevision
    networks:
      - kafka_network
    environment:
      - ZEEVISION_APP_PORT=8080
      - ZEEVISION_API_PORT=8081
      - "ZEEVISION_KAFKA_ADDR=kafka:9093"
      - ZEEVISION_PROD=1
      - ZEEVISION_HOST_APP=1
      - ZEEVISION_HOST_PLAYGROUND=1
    ports:
      - "8080:8080"
      - "8081:8081"

networks:
  kafka_network:
    external: true
