---
version: "3"

services:
  zeevision:
    build: ./
    image: "zeevision:latest"
    container_name: zeevision
    networks:
      - kafka_network
    environment:
      - ZEEVISION_APP_PORT=8080
      - ZEEVISION_API_PORT=8081
      - ZEEVISION_PROD=true
      - "ZEEVISION_KAFKA_ADDR=kafka:9093"
    ports:
      - "8080:8080"
      - "8081:8081"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    ports:
      - "5432:5432"
networks:
  kafka_network:
    external: true
