---
version: "3"

services:
  zeevision:
    build: ./
    image: "zeevision:latest"
    container_name: zeevision
    networks:
      - kafka_network
    environment:
      - ZEEVISION_APP_PORT=8080
      - ZEEVISION_API_PORT=8081
      - "ZEEVISION_KAFKA_ADDR=kafka:9093"
      - ZEEVISION_PROD=0
      - ZEEVISION_HOST_APP=1
      - ZEEVISION_HOST_PLAYGROUND=1
      # Comma separated list of allowed origins for API access.
      # Allow all origins for development.
      - "ZEEVISION_API_ALLOWED_ORIGINS=*"
    ports:
      - "8080:8080"
      - "8081:8081"
  db:
    image: postgres
    restart: always
    networks:
      - kafka_network
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - kafka_network
    environment:
      PGADMIN_DEFAULT_EMAIL: email@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db

networks:
  kafka_network:
    external: true
