---
linters:
  # Disable all default linters to enable each explicitly.
  disable-all: true
  enable:
    - errcheck
    - exhaustive
    - gocyclo
    - gofmt
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
