---
name: Backend

# yamllint disable-line rule:truthy
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: >-
        build-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: >-
        lint-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
          # golangci-lint uses caching internally.
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: ./backend

  test:
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: >-
        test-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Run tests
        working-directory: ./backend
        run: go test -v ./...
