---
name: Configuration

# yamllint disable-line rule:truthy
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  yaml-lint:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
