---
name: Configuration

# yamllint disable-line rule:truthy
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    concurrency:
      group: >-
        yml-lint-${{ github.workflow }}
        -${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
