---
name: Frontend

# yamllint disable-line rule:truthy
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: >-
        build-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: >-
        lint-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (check)
        run: npm run lint

      - name: Run Prettier (check)
        run: npm run prettier

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: >-
        test-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
