name: Frontend - CI/CD with ESLint and Prettier

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  format-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend/zeevision

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install project dependencies
        run: npm install

      - name: Run ESLint (check)
        run: npm run lint

      - name: Run ESLint (fix)
        run: npm run lint:fix

      - name: Run Prettier
        run: npm run prettier
